export default [{
  'categories': [{
    'categories': [{
      'code': '3000',
      'name': '川菜'
    }, {
      'code': '3001',
      'name': '湘菜'
    }, {
      'code': '3002',
      'name': '湖北菜'
    }, {
      'code': '3003',
      'name': '台湾菜'
    }, {
      'code': '3004',
      'name': '新疆菜'
    }, {
      'code': '3005',
      'name': '江浙菜'
    }, {
      'code': '3006',
      'name': '云南菜'
    }, {
      'code': '3007',
      'name': '贵州菜'
    }, {
      'code': '3008',
      'name': '西北菜'
    }, {
      'code': '3009',
      'name': '东北菜'
    }, {
      'code': '3010',
      'name': '香锅/烤鱼'
    }, {
      'code': '3011',
      'name': '海鲜'
    }, {
      'code': '3012',
      'name': '其它地方菜'
    }, {
      'code': '3013',
      'name': '粤菜'
    }, {
      'code': '3014',
      'name': '海南菜'
    }, {
      'code': '3015',
      'name': '鲁菜'
    }, {
      'code': '3016',
      'name': '徽菜'
    }, {
      'code': '3017',
      'name': '晋菜'
    }, {
      'code': '3018',
      'name': '豫菜'
    }, {
      'code': '3019',
      'name': '闽菜'
    }, {
      'code': '3020',
      'name': '上海本帮菜'
    }, {
      'code': '3021',
      'name': '淮扬菜'
    }],
    'code': '2000',
    'name': '中餐'
  }, {
    'categories': [{
      'code': '3022',
      'name': '麻辣烫/串串香'
    }, {
      'code': '3023',
      'name': '川味/重庆火锅'
    }, {
      'code': '3024',
      'name': '云南火锅'
    }, {
      'code': '3025',
      'name': '老北京涮羊肉'
    }, {
      'code': '3026',
      'name': '港式火锅'
    }, {
      'code': '3027',
      'name': '鱼火锅'
    }, {
      'code': '3028',
      'name': '羊蝎子'
    }, {
      'code': '3029',
      'name': '炭火锅'
    }, {
      'code': '3030',
      'name': '韩式火锅'
    }, {
      'code': '3031',
      'name': '豆捞'
    }, {
      'code': '3032',
      'name': '其它火锅'
    }],
    'code': '2001',
    'name': '火锅'
  }, {
    'categories': [{
      'code': '3033',
      'name': '中式烧烤'
    }, {
      'code': '3034',
      'name': '拉美烧烤'
    }, {
      'code': '3035',
      'name': '日式烧烤'
    }, {
      'code': '3036',
      'name': '铁板烧'
    }, {
      'code': '3037',
      'name': '韩式烧烤'
    }, {
      'code': '3038',
      'name': '其它烧烤'
    }],
    'code': '2002',
    'name': '烧烤'
  }, {
    'categories': [{
      'code': '3039',
      'name': '自助餐'
    }, {
      'code': '3040',
      'name': '创意菜'
    }, {
      'code': '3041',
      'name': '西餐'
    }, {
      'code': '3042',
      'name': '日韩料理'
    }, {
      'code': '3043',
      'name': '东南亚菜'
    }, {
      'code': '3044',
      'name': '素食'
    }, {
      'code': '3045',
      'name': '其他餐饮美食'
    }, {
      'code': '3046',
      'name': '清真菜'
    }, {
      'code': '3047',
      'name': '茶餐厅'
    }, {
      'code': '3048',
      'name': '土菜/农家菜'
    }, {
      'code': '3049',
      'name': '采摘/农家乐'
    }],
    'code': '2003',
    'name': '其他美食'
  }, {
    'categories': [{
      'code': '3050',
      'name': '粥'
    }, {
      'code': '3051',
      'name': '汤'
    }, {
      'code': '3052',
      'name': '砂锅/煲类/炖菜'
    }, {
      'code': '3053',
      'name': '其它'
    }],
    'code': '2004',
    'name': '汤/粥/煲/砂锅/炖菜'
  }, {
    'categories': [{
      'code': '3054',
      'name': '西式快餐'
    }, {
      'code': '3055',
      'name': '中式快餐'
    }, {
      'code': '3056',
      'name': '其它快餐'
    }],
    'code': '2005',
    'name': '快餐'
  }, {
    'categories': [{
      'code': '3057',
      'name': '零食'
    }, {
      'code': '3058',
      'name': '生鲜水果'
    }, {
      'code': '3059',
      'name': '其它休闲食品'
    }, {
      'code': '3060',
      'name': '美食特产'
    }],
    'code': '2006',
    'name': '休闲食品'
  }, {
    'categories': [{
      'code': '3061',
      'name': '熟食'
    }, {
      'code': '3062',
      'name': '面点'
    }, {
      'code': '3063',
      'name': '米粉/米线'
    }, {
      'code': '3064',
      'name': '其它小吃'
    }],
    'code': '2007',
    'name': '小吃'
  }, {
    'categories': [{
      'code': '3065',
      'name': '咖啡'
    }, {
      'code': '3066',
      'name': '奶茶'
    }, {
      'code': '3067',
      'name': '冰激凌'
    }, {
      'code': '3068',
      'name': '饮品/甜点'
    }, {
      'code': '3069',
      'name': '咖啡厅'
    }, {
      'code': '3070',
      'name': '酒吧'
    }],
    'code': '2008',
    'name': '休闲茶饮'
  }, {
    'categories': [{
      'code': '3071',
      'name': '蛋糕'
    }, {
      'code': '3072',
      'name': '面包'
    }, {
      'code': '3073',
      'name': '其它烘焙糕点'
    }],
    'code': '2009',
    'name': '烘焙糕点'
  }],
  'code': '1000',
  'name': '餐饮/食品'
}, {
  'categories': [{
    'categories': [{
      'code': '3074',
      'name': '超市'
    }, {
      'code': '3075',
      'name': '个人护理'
    }, {
      'code': '3076',
      'name': '便利店'
    }, {
      'code': '3077',
      'name': '烟酒杂货'
    }, {
      'code': '3078',
      'name': '自动售卖机'
    }],
    'code': '2010',
    'name': '超市便利店'
  }, {
    'categories': [{
      'code': '3207',
      'name': '特色集市'
    }, {
      'code': '3209',
      'name': '菜市场'
    }, {
      'code': '3216',
      'name': '国外代购及免税店'
    }],
    'code': '2031',
    'name': '其他综合零售'
  }, {
    'categories': [{
      'code': '3215',
      'name': '烟花爆竹'
    }],
    'code': '2034',
    'name': '烟花爆竹'
  }, {
    'categories': [{
      'code': '3241',
      'name': '购物中心'
    }, {
      'code': '3242',
      'name': '百货'
    }, {
      'code': '3243',
      'name': '机场'
    }, {
      'code': '3244',
      'name': '火车站'
    }, {
      'code': '3245',
      'name': '商旅文综合体'
    }],
    'code': '2042',
    'name': '百货/商圈/购物中心'
  }, {
    'categories': [{
      'code': '3287',
      'name': '汽车销售'
    }, {
      'code': '3288',
      'name': '二手车销售'
    }, {
      'code': '3289',
      'name': '车饰'
    }, {
      'code': '3290',
      'name': '机动车/配件批发'
    }, {
      'code': '3291',
      'name': '活动房车销售商'
    }, {
      'code': '3292',
      'name': '汽车轮胎经销'
    }, {
      'code': '3293',
      'name': '汽车零配件'
    }, {
      'code': '3294',
      'name': '船舶及配件'
    }, {
      'code': '3295',
      'name': '拖车篷车娱乐用车'
    }, {
      'code': '3296',
      'name': '轨道交通设备器材'
    }, {
      'code': '3297',
      'name': '飞机/配件'
    }, {
      'code': '3298',
      'name': '运输搬运设备'
    }, {
      'code': '3299',
      'name': '起重装卸设备'
    }, {
      'code': '3300',
      'name': '摩托车及配件'
    }, {
      'code': '3301',
      'name': '电动车及配件'
    }, {
      'code': '3302',
      'name': '露营及旅行汽车'
    }, {
      'code': '3303',
      'name': '雪车'
    }],
    'code': '2059',
    'name': '汽车/运输工具/配件'
  }, {
    'categories': [{
      'code': '3304',
      'name': '商务家具批发'
    }, {
      'code': '3305',
      'name': '办公器材批发'
    }, {
      'code': '3306',
      'name': '办公用品文具批发'
    }],
    'code': '2060',
    'name': '办公用品批发'
  }, {
    'categories': [{
      'code': '3307',
      'name': '金属产品/服务'
    }, {
      'code': '3308',
      'name': '电气产品/设备'
    }, {
      'code': '3309',
      'name': '五金器材/用品'
    }, {
      'code': '3310',
      'name': '管道/供暖设备'
    }, {
      'code': '3311',
      'name': '工业设备/制成品'
    }, {
      'code': '3312',
      'name': '工业耐用品'
    }, {
      'code': '3313',
      'name': '化工产品'
    }, {
      'code': '3314',
      'name': '石油/石油产品'
    }],
    'code': '2061',
    'name': '工业产品批发零售'
  }, {
    'categories': [{
      'code': '3315',
      'name': '医疗器械'
    }, {
      'code': '3316',
      'name': '药品批发商'
    }, {
      'code': '3317',
      'name': '康复/身体辅助品'
    }],
    'code': '2062',
    'name': '药品医疗批发'
  }],
  'code': '1001',
  'name': '零售/批发'
}, {
  'categories': [{
    'categories': [{
      'code': '3079',
      'name': '量贩式KTV'
    }, {
      'code': '3080',
      'name': '会所型KTV'
    }, {
      'code': '3081',
      'name': '录音棚'
    }],
    'code': '2011',
    'name': 'K歌'
  }, {
    'categories': [{
      'code': '3082',
      'name': '棋牌休闲'
    }, {
      'code': '3083',
      'name': '中医养生'
    }, {
      'code': '3084',
      'name': '足疗按摩'
    }, {
      'code': '3085',
      'name': '洗浴/桑拿会所'
    }, {
      'code': '3086',
      'name': '网吧网咖'
    }, {
      'code': '3087',
      'name': '游乐游艺'
    }, {
      'code': '3088',
      'name': '图书馆'
    }, {
      'code': '3089',
      'name': '密室'
    }, {
      'code': '3090',
      'name': '桌面游戏'
    }, {
      'code': '3091',
      'name': '真人CS'
    }, {
      'code': '3135',
      'name': '亲子游乐'
    }, {
      'code': '3137',
      'name': '科普场馆'
    }, {
      'code': '3138',
      'name': '亲子DIY'
    }],
    'code': '2012',
    'name': '休闲娱乐'
  }, {
    'categories': [{
      'code': '3092',
      'name': '美甲/手护'
    }, {
      'code': '3093',
      'name': 'SPA/美容/美体'
    }, {
      'code': '3094',
      'name': '美容美发'
    }, {
      'code': '3095',
      'name': '美容美甲'
    }, {
      'code': '3096',
      'name': '美发美甲'
    }, {
      'code': '3097',
      'name': '美发'
    }, {
      'code': '3098',
      'name': '彩妆造型'
    }, {
      'code': '3099',
      'name': '美睫'
    }, {
      'code': '3100',
      'name': '产后塑形'
    }, {
      'code': '3101',
      'name': '纹绣'
    }, {
      'code': '3102',
      'name': '纹身'
    }, {
      'code': '3103',
      'name': '祛痘'
    }, {
      'code': '3104',
      'name': '整形'
    }],
    'code': '2013',
    'name': '美发/美容/美甲'
  }, {
    'categories': [{
      'code': '3105',
      'name': '篮球场'
    }, {
      'code': '3106',
      'name': '舞蹈'
    }, {
      'code': '3107',
      'name': '网球场'
    }, {
      'code': '3108',
      'name': '乒乓球馆'
    }, {
      'code': '3109',
      'name': '游泳馆'
    }, {
      'code': '3110',
      'name': '羽毛球馆'
    }, {
      'code': '3111',
      'name': '桌球馆'
    }, {
      'code': '3112',
      'name': '瑜伽'
    }, {
      'code': '3113',
      'name': '足球场'
    }, {
      'code': '3114',
      'name': '武术场馆'
    }, {
      'code': '3115',
      'name': '溜冰场'
    }, {
      'code': '3116',
      'name': '保龄球馆'
    }, {
      'code': '3117',
      'name': '壁球场'
    }, {
      'code': '3118',
      'name': '排球场'
    }, {
      'code': '3119',
      'name': '高尔夫球场'
    }, {
      'code': '3120',
      'name': '体育场馆'
    }, {
      'code': '3121',
      'name': '健身中心'
    }],
    'code': '2014',
    'name': '运动健身'
  }],
  'code': '1002',
  'name': '娱乐/美容/健身服务'
}, {
  'categories': [{
    'categories': [{
      'code': '3122',
      'name': '宠物店'
    }, {
      'code': '3123',
      'name': '宠物医院'
    }],
    'code': '2015',
    'name': '宠物'
  }, {
    'categories': [{
      'code': '3149',
      'name': '男性服装'
    }, {
      'code': '3150',
      'name': '女性成衣'
    }, {
      'code': '3151',
      'name': '内衣'
    }, {
      'code': '3152',
      'name': '家居服'
    }, {
      'code': '3153',
      'name': '皮草皮具'
    }, {
      'code': '3154',
      'name': '高档时装正装定制'
    }, {
      'code': '3155',
      'name': '裁缝'
    }, {
      'code': '3156',
      'name': '综合服饰'
    }, {
      'code': '3157',
      'name': '儿童服饰'
    }, {
      'code': '3162',
      'name': '剃须刀'
    }, {
      'code': '3163',
      'name': '瑞士军刀'
    }, {
      'code': '3164',
      'name': '烟酒具'
    }, {
      'code': '3165',
      'name': '配饰商店'
    }, {
      'code': '3166',
      'name': '假发'
    }, {
      'code': '3167',
      'name': '饰物'
    }, {
      'code': '3168',
      'name': '鞋类'
    }, {
      'code': '3169',
      'name': '行李箱包'
    }],
    'code': '2020',
    'name': '服饰/箱包/饰品'
  }, {
    'categories': [{
      'code': '3158',
      'name': '化妆品'
    }],
    'code': '2021',
    'name': '美妆/护肤'
  }, {
    'categories': [{
      'code': '3159',
      'name': '珠宝'
    }, {
      'code': '3160',
      'name': '金银'
    }],
    'code': '2022',
    'name': '黄金珠宝/钻石/玉石'
  }, {
    'categories': [{
      'code': '3161',
      'name': '钟表店'
    }, {
      'code': '3208',
      'name': '眼镜店'
    }],
    'code': '2023',
    'name': '钟表/眼镜'
  }, {
    'categories': [{
      'code': '3170',
      'name': '婚庆用品'
    }],
    'code': '2024',
    'name': '婚庆用品'
  }, {
    'categories': [{
      'code': '3171',
      'name': '母婴用品/儿童玩具'
    }],
    'code': '2025',
    'name': '母婴用品/儿童玩具'
  }, {
    'categories': [{
      'code': '3172',
      'name': '运动户外安防用品'
    }],
    'code': '2026',
    'name': '户外/运动/健身器材/安防'
  }, {
    'categories': [{
      'code': '3173',
      'name': '文具'
    }, {
      'code': '3174',
      'name': '乐器'
    }, {
      'code': '3175',
      'name': '二手商品店'
    }, {
      'code': '3176',
      'name': '文物古董'
    }, {
      'code': '3177',
      'name': '古玩复制品'
    }, {
      'code': '3178',
      'name': '礼品'
    }, {
      'code': '3179',
      'name': '卡片'
    }, {
      'code': '3180',
      'name': '纪念品'
    }, {
      'code': '3181',
      'name': '瓷器'
    }, {
      'code': '3182',
      'name': '玻璃和水晶摆件'
    }, {
      'code': '3183',
      'name': '工艺美术用品'
    }, {
      'code': '3184',
      'name': '艺术品和画廊'
    }, {
      'code': '3185',
      'name': '邮票/纪念币'
    }, {
      'code': '3186',
      'name': '宗教物品'
    }],
    'code': '2027',
    'name': '文化艺术店'
  }, {
    'categories': [{
      'code': '3187',
      'name': '手机'
    }, {
      'code': '3188',
      'name': '通讯设备'
    }, {
      'code': '3189',
      'name': '数码产品及配件'
    }, {
      'code': '3190',
      'name': '专业摄影器材'
    }, {
      'code': '3191',
      'name': '计算机/服务器'
    }, {
      'code': '3192',
      'name': '打字/打印/扫描'
    }, {
      'code': '3193',
      'name': '家用电器'
    }],
    'code': '2028',
    'name': '数码家电/办公设备'
  }, {
    'categories': [{
      'code': '3194',
      'name': '草坪和花园用品'
    }, {
      'code': '3195',
      'name': '地毯窗帘等家纺'
    }, {
      'code': '3196',
      'name': '帷幕'
    }, {
      'code': '3197',
      'name': '室内装潢壁炉'
    }, {
      'code': '3198',
      'name': '屏风'
    }, {
      'code': '3199',
      'name': '家庭装饰'
    }, {
      'code': '3200',
      'name': '花木栽种用品'
    }],
    'code': '2029',
    'name': '家居家纺'
  }, {
    'categories': [{
      'code': '3201',
      'name': '油漆'
    }, {
      'code': '3202',
      'name': '清漆用品'
    }, {
      'code': '3203',
      'name': '大型建材卖场卖场'
    }, {
      'code': '3204',
      'name': '木材与建材商店'
    }, {
      'code': '3205',
      'name': '玻璃'
    }, {
      'code': '3206',
      'name': '墙纸'
    }],
    'code': '2030',
    'name': '建材'
  }, {
    'categories': [{
      'code': '3210',
      'name': '计生用品'
    }],
    'code': '2032',
    'name': '计生用品'
  }, {
    'categories': [{
      'code': '3211',
      'name': '音像制品租售'
    }, {
      'code': '3212',
      'name': '音像制品/书籍'
    }, {
      'code': '3213',
      'name': '书籍'
    }, {
      'code': '3214',
      'name': '报纸杂志'
    }],
    'code': '2033',
    'name': '报刊/音像/书籍'
  }, {
    'categories': [{
      'code': '3330',
      'name': '鲜花/盆栽'
    }],
    'code': '2072',
    'name': '鲜花/盆栽'
  }],
  'code': '1003',
  'name': '生活/家居'
}, {
  'categories': [{
    'categories': [{
      'code': '3124',
      'name': '婚礼策划'
    }, {
      'code': '3125',
      'name': '婚纱/礼服'
    }, {
      'code': '3126',
      'name': '婚车租赁'
    }, {
      'code': '3127',
      'name': '旅拍/本地婚纱摄影'
    }, {
      'code': '3128',
      'name': '本地婚纱摄影'
    }, {
      'code': '3129',
      'name': '儿童摄影'
    }, {
      'code': '3130',
      'name': '孕妇摄影'
    }, {
      'code': '3131',
      'name': '艺术写真'
    }, {
      'code': '3132',
      'name': '跟拍'
    }, {
      'code': '3133',
      'name': '证件照'
    }, {
      'code': '3134',
      'name': '商业摄影'
    }, {
      'code': '3360',
      'name': '婚纱摄影'
    }],
    'code': '2016',
    'name': '婚庆/摄影'
  }, {
    'categories': [{
      'code': '3136',
      'name': '亲子游泳'
    }, {
      'code': '3142',
      'name': '亲子服务'
    }, {
      'code': '3143',
      'name': '产后恢复'
    }, {
      'code': '3144',
      'name': '月子服务'
    }],
    'code': '2017',
    'name': '亲子服务'
  }, {
    'categories': [{
      'code': '3145',
      'name': '洗衣家纺'
    }, {
      'code': '3146',
      'name': '鞋帽清洗'
    }, {
      'code': '3147',
      'name': '奢侈品养护'
    }, {
      'code': '3148',
      'name': '自助洗衣'
    }],
    'code': '2019',
    'name': '洗衣'
  }, {
    'categories': [{
      'code': '3217',
      'name': '咨询/法律咨询/金融咨询'
    }],
    'code': '2035',
    'name': '咨询/法律咨询/金融咨询'
  }, {
    'categories': [{
      'code': '3218',
      'name': '洗车'
    }, {
      'code': '3220',
      'name': '拖车'
    }, {
      'code': '3221',
      'name': '维修'
    }, {
      'code': '3222',
      'name': '保养'
    }, {
      'code': '3223',
      'name': '汽车美容'
    }, {
      'code': '3331',
      'name': '送水站'
    }, {
      'code': '3332',
      'name': '搬家'
    }, {
      'code': '3333',
      'name': '回收'
    }, {
      'code': '3334',
      'name': '开锁'
    }, {
      'code': '3335',
      'name': '管道疏通'
    }, {
      'code': '3336',
      'name': '家电维修'
    }, {
      'code': '3337',
      'name': '焊接维修'
    }, {
      'code': '3338',
      'name': '家居维修、翻新'
    }, {
      'code': '3348',
      'name': '家政'
    }, {
      'code': '3355',
      'name': '灭虫/消毒'
    }, {
      'code': '3356',
      'name': '清洁/保养/门卫'
    }],
    'code': '2036',
    'name': '家政/维修服务'
  }, {
    'categories': [{
      'code': '3323',
      'name': '装饰/设计'
    }],
    'code': '2065',
    'name': '装饰/设计'
  }, {
    'categories': [{
      'code': '3354',
      'name': '广告/会展/活动策划'
    }],
    'code': '2081',
    'name': '广告/会展/活动策划'
  }, {
    'categories': [{
      'code': '3357',
      'name': '农业合作与农具'
    }],
    'code': '2082',
    'name': '农业合作与农具'
  }, {
    'categories': [{
      'code': '3358',
      'name': '丧仪殡葬服务'
    }],
    'code': '2083',
    'name': '丧仪殡葬服务'
  }],
  'code': '1004',
  'name': '生活/咨询服务'
}, {
  'categories': [{
    'categories': [{
      'code': '3139',
      'name': '早教中心'
    }, {
      'code': '3140',
      'name': '少儿外语'
    }, {
      'code': '3141',
      'name': '少儿才艺'
    }, {
      'code': '3227',
      'name': '职业技术培训'
    }, {
      'code': '3228',
      'name': '外语'
    }, {
      'code': '3229',
      'name': '音乐'
    }, {
      'code': '3230',
      'name': '升学辅导'
    }, {
      'code': '3231',
      'name': '体育'
    }, {
      'code': '3232',
      'name': '美术'
    }, {
      'code': '3233',
      'name': '留学'
    }, {
      'code': '3234',
      'name': '驾校'
    }, {
      'code': '3235',
      'name': '兴趣生活'
    }, {
      'code': '3238',
      'name': '成人教育/函授'
    }, {
      'code': '3239',
      'name': '商业/文秘学校'
    }],
    'code': '2018',
    'name': '教育/培训/考试缴费/学费'
  }, {
    'categories': [{
      'code': '3236',
      'name': '中小学校'
    }, {
      'code': '3237',
      'name': '大学与学院'
    }, {
      'code': '3240',
      'name': '儿童保育/学前'
    }],
    'code': '2041',
    'name': '私立院校'
  }, {
    'categories': [{
      'code': '3361',
      'name': '中小学校'
    }, {
      'code': '3362',
      'name': '大学与学院'
    }, {
      'code': '3363',
      'name': '儿童保育/学前'
    }],
    'code': '2084',
    'name': '公立院校'
  }],
  'code': '1005',
  'name': '教育/培训'
}, {
  'categories': [{
    'categories': [{
      'code': '3219',
      'name': '保险业务'
    }],
    'code': '2037',
    'name': '保险业务'
  }],
  'code': '1006',
  'name': '金融'
}, {
  'categories': [{
    'categories': [{
      'code': '3224',
      'name': '汽车租赁'
    }, {
      'code': '3276',
      'name': '租车'
    }],
    'code': '2038',
    'name': '租车'
  }, {
    'categories': [{
      'code': '3226',
      'name': '加油'
    }],
    'code': '2040',
    'name': '加油'
  }, {
    'categories': [{
      'code': '3273',
      'name': '货运代理/报关行'
    }],
    'code': '2049',
    'name': '货运代理/报关行'
  }, {
    'categories': [{
      'code': '3274',
      'name': '铁路客运'
    }],
    'code': '2050',
    'name': '铁路客运'
  }, {
    'categories': [{
      'code': '3275',
      'name': '公共交通'
    }],
    'code': '2051',
    'name': '公共交通'
  }, {
    'categories': [{
      'code': '3277',
      'name': '长途公路客运'
    }],
    'code': '2052',
    'name': '长途公路客运'
  }, {
    'categories': [{
      'code': '3278',
      'name': '游轮/巡游航线'
    }],
    'code': '2053',
    'name': '游轮/巡游航线'
  }, {
    'categories': [{
      'code': '3279',
      'name': '出租船只'
    }],
    'code': '2054',
    'name': '出租船只'
  }, {
    'categories': [{
      'code': '3280',
      'name': '港口经营\\港口理货'
    }],
    'code': '2055',
    'name': '港口经营\\港口理货'
  }, {
    'categories': [{
      'code': '3282',
      'name': '贵宾服务'
    }, {
      'code': '3283',
      'name': '行李打包'
    }, {
      'code': '3284',
      'name': 'wifi租赁'
    }],
    'code': '2057',
    'name': '机场服务'
  }, {
    'categories': [{
      'code': '3285',
      'name': '高铁贵宾服务'
    }, {
      'code': '3286',
      'name': '高铁行李打包'
    }],
    'code': '2058',
    'name': '高铁服务'
  }, {
    'categories': [{
      'code': '3343',
      'name': '物流货运'
    }, {
      'code': '3344',
      'name': '铁路货运'
    }, {
      'code': '3345',
      'name': '公共仓储'
    }, {
      'code': '3346',
      'name': '集装整理'
    }, {
      'code': '3347',
      'name': '快递服务'
    }],
    'code': '2075',
    'name': '物流/快递'
  }],
  'code': '1007',
  'name': '交通运输服务类'
}, {
  'categories': [{
    'categories': [{
      'code': '3225',
      'name': '停车缴费'
    }],
    'code': '2039',
    'name': '停车缴费'
  }, {
    'categories': [{
      'code': '3281',
      'name': '路桥通行费'
    }],
    'code': '2056',
    'name': '路桥通行费'
  }, {
    'categories': [{
      'code': '3339',
      'name': '电力缴费'
    }, {
      'code': '3340',
      'name': '煤气缴费'
    }, {
      'code': '3341',
      'name': '自来水缴费'
    }, {
      'code': '3384',
      'name': '交通罚款'
    }],
    'code': '2073',
    'name': '水电煤缴费/交通罚款等生活缴费'
  }, {
    'categories': [{
      'code': '3342',
      'name': '物业管理费'
    }],
    'code': '2074',
    'name': '物业管理费'
  }],
  'code': '1008',
  'name': '生活缴费'
}, {
  'categories': [{
    'categories': [{
      'code': '3246',
      'name': '社区医院'
    }, {
      'code': '3247',
      'name': '正骨医生'
    }, {
      'code': '3248',
      'name': '按摩医生'
    }, {
      'code': '3249',
      'name': '眼科医疗服务'
    }, {
      'code': '3250',
      'name': '手足病医疗服务'
    }, {
      'code': '3251',
      'name': '护理/照料服务'
    }, {
      'code': '3252',
      'name': '中医'
    }, {
      'code': '3253',
      'name': '齿科'
    }, {
      'code': '3254',
      'name': '药店'
    }, {
      'code': '3255',
      'name': '急救服务'
    }, {
      'code': '3256',
      'name': '妇幼医院'
    }, {
      'code': '3257',
      'name': '体检中心'
    }],
    'code': '2043',
    'name': '私立/民营医院/诊所'
  }, {
    'categories': [{
      'code': '3364',
      'name': '手足病医疗服务'
    }, {
      'code': '3365',
      'name': '社区医院'
    }, {
      'code': '3366',
      'name': '眼科医疗服务'
    }, {
      'code': '3367',
      'name': '护理/照料服务'
    }, {
      'code': '3368',
      'name': '公立医院'
    }, {
      'code': '3369',
      'name': '中医'
    }, {
      'code': '3370',
      'name': '齿科'
    }, {
      'code': '3371',
      'name': '药店'
    }, {
      'code': '3372',
      'name': '急救服务'
    }, {
      'code': '3373',
      'name': '妇幼医院'
    }, {
      'code': '3374',
      'name': '体检中心'
    }],
    'code': '2085',
    'name': '公立医院'
  }],
  'code': '1009',
  'name': '医疗'
}, {
  'categories': [{
    'categories': [{
      'code': '3258',
      'name': '门票'
    }, {
      'code': '3259',
      'name': '景区生活服务'
    }, {
      'code': '3260',
      'name': '景区购物'
    }],
    'code': '2044',
    'name': '景区'
  }, {
    'categories': [{
      'code': '3261',
      'name': '客栈单体'
    }, {
      'code': '3262',
      'name': '客栈连锁'
    }, {
      'code': '3264',
      'name': '酒店单体'
    }, {
      'code': '3265',
      'name': '酒店连锁'
    }, {
      'code': '3267',
      'name': '酒店式公寓'
    }, {
      'code': '3268',
      'name': '度假别墅服务'
    }, {
      'code': '3269',
      'name': '运动和娱乐露营'
    }, {
      'code': '3270',
      'name': '活动房车和野营'
    }],
    'code': '2045',
    'name': '旅馆/酒店/度假区'
  }, {
    'categories': [{
      'code': '3263',
      'name': '交通票务'
    }, {
      'code': '3359',
      'name': '娱乐票务'
    }],
    'code': '2046',
    'name': '票务'
  }, {
    'categories': [{
      'code': '3266',
      'name': '旅行社'
    }],
    'code': '2047',
    'name': '旅行社'
  }, {
    'categories': [{
      'code': '3271',
      'name': '航空公司'
    }, {
      'code': '3272',
      'name': '机票平台'
    }],
    'code': '2048',
    'name': '机票/机票代理'
  }],
  'code': '1010',
  'name': '票务/旅游'
}, {
  'categories': [{
    'categories': [{
      'code': '3318',
      'name': '慈善/社会公益'
    }, {
      'code': '3319',
      'name': '行业协会/社团'
    }, {
      'code': '3320',
      'name': '宗教组织'
    }],
    'code': '2063',
    'name': '社会组织'
  }, {
    'categories': [{
      'code': '3375',
      'name': '法庭费用'
    }, {
      'code': '3376',
      'name': '行政费用和罚款'
    }, {
      'code': '3377',
      'name': '保释金'
    }, {
      'code': '3378',
      'name': '税务/海关'
    }, {
      'code': '3379',
      'name': '社会保障服务'
    }, {
      'code': '3380',
      'name': '使领馆'
    }, {
      'code': '3381',
      'name': '国家邮政'
    }, {
      'code': '3382',
      'name': '政府采购'
    }, {
      'code': '3383',
      'name': '政府贷款'
    }],
    'code': '2086',
    'name': '政府服务'
  }],
  'code': '1011',
  'name': '政府/社会组织'
}, {
  'categories': [{
    'categories': [{
      'code': '3321',
      'name': '电影院'
    }, {
      'code': '3322',
      'name': '私人影院'
    }],
    'code': '2064',
    'name': '游艺厅/KTV/网吧'
  }],
  'code': '1012',
  'name': '娱乐/健身服务'
}, {
  'categories': [{
    'categories': [{
      'code': '3324',
      'name': '电信运营商'
    }],
    'code': '2066',
    'name': '电信运营商'
  }, {
    'categories': [{
      'code': '3325',
      'name': '话费充值与缴费'
    }],
    'code': '2067',
    'name': '话费充值与缴费'
  }, {
    'categories': [{
      'code': '3326',
      'name': '互联网IDC服务'
    }],
    'code': '2068',
    'name': '互联网IDC服务'
  }, {
    'categories': [{
      'code': '3327',
      'name': '网络电话传真'
    }],
    'code': '2069',
    'name': '网络电话传真'
  }, {
    'categories': [{
      'code': '3328',
      'name': '通信营业厅'
    }],
    'code': '2070',
    'name': '通信营业厅'
  }, {
    'categories': [{
      'code': '3329',
      'name': '付费电话'
    }],
    'code': '2071',
    'name': '付费电话'
  }],
  'code': '1013',
  'name': '通信'
}, {
  'categories': [{
    'categories': [{
      'code': '3349',
      'name': '门户/资讯/论坛'
    }],
    'code': '2076',
    'name': '门户/资讯/论坛'
  }, {
    'categories': [{
      'code': '3350',
      'name': '软件/建站/技术开发'
    }],
    'code': '2077',
    'name': '软件/建站/技术开发'
  }, {
    'categories': [{
      'code': '3351',
      'name': '游戏'
    }],
    'code': '2078',
    'name': '游戏'
  }, {
    'categories': [{
      'code': '3352',
      'name': '在线图书/视频/音乐'
    }],
    'code': '2079',
    'name': '在线图书/视频/音乐'
  }, {
    'categories': [{
      'code': '3353',
      'name': '网络推广/网络广告'
    }],
    'code': '2080',
    'name': '网络推广/网络广告'
  }],
  'code': '1014',
  'name': '网络虚拟服务'
}]
